config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "events#index"

  resources :events, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  resources :users, only: [:show]
  resources :enrollments, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, :body, :location, :date, presence: true

  belongs_to :creator, class_name: "User"
  has_many :enrollments
  has_many :attendees, through: :enrollments, source: :user

  scope :past, -> { where("date < ?", Date.today) }
  scope :future, -> { where("date > ?", Date.today) }
  scope :today, -> { where("date = ?", Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :email, :password, :password_confirmation, presence: true
  validates :email, uniqueness: true
  validates :username, uniqueness: true

  # Creator association
  has_many :events, foreign_key: "creator_id", class_name: "Event"

  # Attendees association
  has_many :enrollments
  has_many :attended_events, through: :enrollments, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def require_login
    if !current_user.present?
      flash[:alert] = "You must be logged in to view this page"
      redirect_to root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :current_password])
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :require_login

  def create
    # TO DO
    #   - Check if the current user posted the event before being allowed to enrol in it
    #     if current_user.id == @enrollment.event.id

    @enrollment = Enrollment.new(user_id: current_user.id, event_id: params[:event_id])

    # check the current user's enrollments to see if they have previously enrolled for this specific event
    enr_find = current_user.enrollments.any? do |enr|
      enr.event_id == params[:event_id].to_i
    end

    # if the user has not previously enrolled with this event, proceed with saving the enrollment
    if !enr_find && current_user.id != @enrollment.event.creator.id
      if @enrollment.save
        flash[:notice] = "Congratulations, you are now attending this event!"
      else
        flash[:alert] = "Sorry! Something went wrong while finalizing your attendance, please try again later"
      end
    else
      # If the user has previously enrolled in this event, redirect them back the the event page with an error message
      flash[:notice] = "You have already enrolled in this event!"
    end

    redirect_to event_path(params[:event_id])
  end

  def destroy
    @enrollment = Enrollment.find(params[:id])
    usr = @enrollment.user
    @enrollment.destroy

    redirect_to user_path(usr)
  end

  private
  def enrollment_params
    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_login, except: [:index, :show]

  def index
    @events = Event.all.includes(:creator)
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    # add before_action to limit :new, :create to only logged in users
    @event = current_user.events.build(event_parameters)
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to user_path(current_user), status: :see_other
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_parameters)
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

    def event_parameters
      params.require(:event).permit(:title, :body, :location, :date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>EVENT EDIT PAGE</h1>

<%= render partial: "shared/new-event-form", locals: { event: @event } %>
<%= link_to "Back to event page", event_path(@event) %>

app/views/events/index.html.erb
<h1>EVENT INDEX PAGE</h1>
<%= link_to "Post new event", new_event_path %>

<% if !Event.today.empty? %>
  <div>
    <h2>Today's events: </h2>
    <% Event.today.each do |ev| %>
      <%= render partial: "shared/display-event", locals: { :ev => ev } %>
      <div><%= link_to "Show Details", event_path(ev) %></div><br>
    <% end %>
  </div>
<% end %>

<% if !Event.future.empty? %>
  <div>
    <h2>Future events: </h2>
      <% Event.future.each do |ev| %>
      <%= render partial: "shared/display-event", locals: { :ev => ev } %>
      <div><%= link_to "Show Details", event_path(ev) %></div><br>
    <% end %>
  </div>
<% end %>

<% if !Event.past.empty? %>
  <div>
    <h2>Past events: </h2>
      <% Event.past.each do |ev| %>
      <%= render partial: "shared/display-event", locals: { :ev => ev } %>
      <div><%= link_to "Show Details", event_path(ev) %></div><br>
    <% end %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>EVENT CREATION FORM</h1>

<%= render partial: "shared/new-event-form", locals: { event: @event } %>

app/views/events/show.html.erb
<h1>EVENT SHOW PAGE</h1>
<%= render partial: "shared/display-event", locals: { :ev => @event } %>

<%# if the user isn't the owner of the event... %>
<% if current_user != @event.creator && current_user.present? %>
  <% existing_enrollment = current_user.enrollments.any? { |enr| enr.event_id == @event.id } %>

  <%# and the user has no previous enrollments in this event... %>
  <% if !existing_enrollment %>
    <%# ... then let them enroll in the event %>
    <%= form_with url: enrollments_path, method: :post do |f| %>
      <%= f.hidden_field :event_id, value: params[:id] %>
      <%= f.submit value: "Attend this event"  %>
    <% end %>
  <% end %>
<% end %>

<% if current_user == @event.creator %>
  <div>
    <%= link_to "Delete this event", event_path(@event), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </div>

  <div>
    <%= link_to "Edit this event", edit_event_path(@event) %>
  </div>
<% end %>

<h2>Others going to this event: </h2>
<ul>
  <% @event.attendees.each do |att| %>
    <li><%= link_to att.username, user_path(att) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/show-user" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/shared/_display-event.html.erb
<div><strong><%= ev.title %></strong></div>
<div><%= ev.body %></div>
<div><strong>Location:</strong> <%= ev.location %></div>
<div><strong>Scheduled Date:</strong> <%= ev.date %> <%= render partial: "shared/event-future-past", locals: { ev: ev } %></div>
<div><strong>Posted by:</strong> <%= ev.creator.username %> <%= " (You)" if ev.creator == current_user %></div>

app/views/shared/_event-future-past.html.erb
<% if ev.date > Date.today %>
  (future event)
<% elsif ev.date < Date.today %>
  (past event)
<% else %>
  (today)
<% end %>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign out", destroy_user_session_path, data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></li>
    <li><%= link_to "Homepage", root_path %></li>
  </ul>
</nav>

app/views/shared/_new-event-form.html.erb
<%= form_with model: event do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.date_field :date, min: Date.today %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body, cols: 35, rows: 8 %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/shared/_show-user.html.erb
<div>Welcome <%= user_signed_in? ? current_user.username : "Stranger" %></div>

app/views/users/show.html.erb
<h1>USER SHOW PAGE</h1>
<div><%= @user.username %></div>
<div><%= @user.email %></div>

<div>
  <h2><%= @user.username %>'s Listed Events: </h2>
  <ul>
    <% @user.events.each do |ev| %>
      <li>
        <%= ev.title %>
        <%= link_to "Show details", event_path(ev) %>
      </li>
    <% end %>
  </ul>
</div>

<div>
  <h2><%= @user.username %> is attending these events: </h2>
  <ul>
    <% @user.attended_events.each do |ev| %>
      <li>
        <%= ev.title %>
        <%= render partial: "shared/event-future-past", locals: { ev: ev } %>
        <%= link_to "See Details", event_path(ev) %>

        <%# if the logged in user is the same as the user being shown, then allow the user to remove their enrollments %>

        <% if !current_user.nil? && current_user.id == @user.id %>
          <% enr = @user.enrollments.find_by(event_id: ev.id) %>
          <%= link_to "Withdraw your enrollment", enrollment_path(enr), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>